load("@rules_java//java:java_library.bzl", "java_library")

java_library(
    name = "data",
    visibility = ["//visibility:public"],
    srcs = glob(["*.java"]),
    deps = ["//eflect/src/main/java/eflect/util"]
)
