TEST_SRCS = [
    "//src/main/java/flora",
    "//src/main/java/flora/context",
    "//src/main/java/flora/knob",
    "//src/main/java/flora/strategy/archiving",
]

java_test(
    name = "ArchivingStrategyTest",
    srcs = ["ArchivingStrategyTest.java"],
    deps = TEST_SRCS,
)

