TEST_SRCS = [
    "//src/main/java/flora",
    "//src/main/java/flora/meter",
]

java_test(
    name = "SnapshotMeterTest",
    srcs = ["SnapshotMeterTest.java"],
    deps = TEST_SRCS,
)

java_test(
    name = "StopwatchTest",
    srcs = ["StopwatchTest.java"],
    deps = TEST_SRCS,
)
