java_test(
    name = "SummaryTest",
    srcs = ["SummaryTest.java"],
    test_class = "flora.examples.toggle.SummaryTest",
    deps = [
        "//examples/main/java/flora/examples/toggle",
        "//src/main/java/flora/strategy/archiving",
    ],
)

java_test(
    name = "OptimizerTest",
    srcs = ["OptimizerTest.java"],
    test_class = "flora.examples.toggle.OptimizerTest",
    deps = [
        "//examples/main/java/flora/examples/toggle",
        "//src/main/java/flora/strategy/mab",
        "//src/main/java/flora/strategy/mab/exploit",
        "//src/main/java/flora/strategy/mab/epsilon",
    ],
)