java_library(
    name = "mab",
    visibility = ["//visibility:public"],
    srcs = glob(["*.java"]),
    deps = [
        "//src/main/java/flora",
        "//src/main/java/flora/context",
        "//src/main/java/flora/knob",
        "//src/main/java/flora/strategy",
    ],
)