java_library(
    name = "eflect",
    visibility = ["//visibility:public"],
    srcs = glob(["*.java"]),
    deps = [
        "//src/main/java/flora",
        "//src/main/java/flora/fault",
        "//src/main/java/flora/util",
        "//eflect/src/main/java/eflect",
        "//eflect/src/main/java/eflect/data",
        "//eflect/src/main/java/eflect/util",
    ]
)
