TEST_SRCS = [
    "//src/main/java/flora",
    "//src/main/java/flora/knob",
]

java_test(
    name = "BooleanKnobTest",
    srcs = ["BooleanKnobTest.java"],
    deps = TEST_SRCS,
)

java_test(
    name = "EnumKnobTest",
    srcs = ["EnumKnobTest.java"],
    deps = TEST_SRCS,
)

java_test(
    name = "IntCollectionKnobTest",
    srcs = ["IntCollectionKnobTest.java"],
    deps = TEST_SRCS,
)

java_test(
    name = "IntRangeKnobTest",
    srcs = ["IntRangeKnobTest.java"],
    deps = TEST_SRCS,
)