java_library(
    name = "strategy",
    visibility = ["//visibility:public"],
    srcs = glob(["*.java"]),
    deps = [
        "//src/main/java/green",
        "//src/main/java/green/knob",
    ],
)