TEST_SRCS = [
    "//src/main/java/flora",
    "//src/main/java/flora/knob",
]

java_test(
    name = "JsonKnobUtilTest",
    srcs = ["JsonKnobUtilTest.java"],
    deps = [
        "//src/main/java/flora/knob",
        "//src/main/java/flora/knob/util:json",
        "@maven//:org_json_json",
    ],
)
