syntax = "proto3";

package flora.experiments.rendering;

option java_multiple_files = true;
option java_package = "flora.experiments.rendering";

import "experiments/main/proto/knob.proto";

service FloraRenderingProblemService {
  rpc NextConfiguration (Empty) returns (RenderingConfiguration) {}
  rpc Evaluate (RenderingScore) returns (Empty) {}
}

message Empty {}

message RenderingKnobs {
  // Image width.
  optional knob.RangeKnob resolution_x = 1;
  // Image height.
  optional knob.RangeKnob resolution_y = 2;
  // Anti-aliasing minimum
  optional knob.RangeKnob aa_samples = 3;
  // Ambient occlusion samples
  optional knob.RangeKnob ao_samples = 4;
  // Rendering filter
  repeated string filter = 5;
  // Number of threads
  optional knob.RangeKnob threads = 6;
}

message RenderingConfiguration {
  // Image width.
  optional int64 resolution_x = 1;
  // Image height.
  optional int64 resolution_y = 2;
  // Anti-aliasing minimum
  // Anti-aliasing minimum
  optional int64 aa_samples = 3;
  // Ambient occlusion samples
  optional int64 ao_samples = 4;
  // Rendering filter
  optional string filter = 5;
  // Number of threads
  optional int64 threads = 6;
}

message RenderingScore {
  optional double energy = 1;
  optional double runtime = 2;
  optional double mse = 3;
  optional double piqe = 4;
  optional double brisque = 5;
}
