syntax = "proto3";

package flora.experiments.rendering;

option java_multiple_files = true;
option java_package = "flora.experiments.rendering";

import "experiments/main/proto/knob.proto";

service FloraRenderingProblemService {
  rpc NextConfiguration (Empty) returns (RenderingConfiguration) {}
  rpc Evaluate (RenderingScore) returns (Empty) {}
}

message Empty {}

message RenderingKnobs {
  // Image width.
  optional knob.RangeKnob resolution_x = 1;
  // Image height.
  optional knob.RangeKnob resolution_y = 2;
  // Anti-aliasing minimum
  optional knob.RangeKnob aa_samples = 3;
  // Ambient occlusion samples
  optional knob.RangeKnob ao_samples = 4;
  // Rendering filter
  repeated string filter = 5;
  // Number of threads (only for CPU experiments)
  optional knob.RangeKnob threads = 6;
}

message RenderingConfiguration {
  // Image width.
  optional int64 resolution_x = 1;
  // Image height.
  optional int64 resolution_y = 2;
  // Anti-aliasing minimum
  // Anti-aliasing minimum
  optional int64 aa_samples = 3;
  // Ambient occlusion samples
  optional int64 ao_samples = 4;
  // Rendering filter
  optional string filter = 5;
  // Number of threads (only for CPU experiments)
  optional int64 threads = 6;
}

message RenderingScore {
  // CPU energy
  optional double cpu_energy = 1;
  // GPU energy
  optional double gpu_energy = 2;
  // Sum of energies
  optional double energy = 3;
  // Duration of rendering
  optional double runtime = 4;
  // PIQE score, please read https://www.mathworks.com/help/images/ref/piqe.html
  optional double piqe = 5;
  // BRISQUE score, please read https://www.mathworks.com/help/images/ref/brisque.html
  optional double brisque = 6;
  // Mean squared error metric, please read https://quality.nfdi4ing.de/en/latest/image_quality/MeanSquared_Error.html
  optional double mse = 7 [deprecated = true];
}
