java_library(
    name = "contrib",
    visibility = ["//visibility:public"],
    srcs = glob(["*.java"]),
    deps = [
        "//src/main/java/flora",
        "//eflect/src/main/java/eflect",
        "//eflect/src/main/protobuf/eflect:eflect_java_protos",
    ]
)
