load("@rules_java//java:java_library.bzl", "java_library")

java_library(
    name = "meta",
    visibility = ["//visibility:public"],
    srcs = glob(["*.java"]),
    deps = ["//src/main/java/flora"],
)
