TEST_SRCS = [
    "//src/main/java/flora",
    "//src/main/java/flora/strategy",
    "//src/main/java/flora/testing",
]

java_test(
    name = "ArchivingStrategyTest",
    srcs = ["ArchivingStrategyTest.java"],
    deps = TEST_SRCS,
)

