java_test(
    name = "MachineRunnerTest",
    srcs = ["MachineRunnerTest.java"],
    deps = [
        "//src/main/java/flora",
        "//src/main/java/flora/machine",
        "//src/main/java/flora/testing",
    ],
)